---

- name: Configure EC2 instance
  hosts: lb
  user: ec2-user
#  connection: ssh
  become: true


  tasks:
  - name: Update the machine
    command: sudo yum update -y
    
  - name: Installing essentials
    command: yum  install apt-transport-https ca-certificates curl software-properties-common -y
      
  - name: Installing Curl
    command: yum install curl -y
  
  - name: Installing docker
    command: yum install docker -y

  - name: Adding user to group
    command: sudo usermod -aG docker ${USER}

  - name: Restarting docker service
    command: sudo service docker restart 

  - name: Updating the machine 2
    command: sudo yum update

  - name: Installing Python Pip
    command: sudo yum  install python-pip python-dev build-essential -y

  - name: Installing Docker compose
    command: sudo pip install docker-compose==1.3.0
    
  - name: retry if needed using command apt-get update
    command: yum update
    become: yes
 
 # - name: install Docke-py
  #  command: sudo pip install docker-py

  - name: update instance
    command: yum update
    become: yes
